#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

// Binding 0 : Position storage buffer
layout(std140, binding = 0) buffer Height 
{
   float height[];
};

layout (local_size_x = 16, local_size_y = 16) in;

layout (binding = 1) uniform UBO 
{
	float time;
	float dx;
} ubo;

void main() 
{
    // Current SSBO index
    uint index = gl_GlobalInvocationID.x;	

    float value = 1.0;

    // Write back
    height[index] = value;
}